[package]
name = "mini-nav-mapping"
version = "0.1.0"
edition = "2024"
description = "Package for implementing mapping"
readme = "../../README.md"
repository = "https://github.com/sachinkum0009/mini-nav"
license = "Apache-2.0"
keywords = ["mininav", "mapping", "navigation"]

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
hiroz = { git = "https://github.com/ZettaScaleLabs/hiroz.git", branch = "main"}
hiroz-msgs = { git = "https://github.com/ZettaScaleLabs/hiroz.git", branch = "main"}
mini-nav-controller = { path = "../mini-nav-controller" }
nalgebra = "0.35.0"
rayon = "1.12.0"

[[bin]]
name = "mapping_test"
path = "bin/mapping_test.rs"
