[package]
name = "mini-nav-planner"
version = "0.1.0"
edition = "2024"
description = "Package for implementing planner"
readme = "../../README.md"
repository = "https://github.com/sachinkum0009/mini-nav"
license = "Apache-2.0"
keywords = ["mininav", "planner", "navigation"]

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
