[package]
name = "mini-nav"
version = "0.1.0"
edition = "2024"
description = "Package for using navigation"
readme = "README.md"
repository = "https://github.com/sachinkum0009/mini-nav"
license = "Apache-2.0"
keywords = ["mininav", "robotics", "navigation"]

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
hiroz = { git = "https://github.com/ZettaScaleLabs/hiroz.git", branch = "main"}
hiroz-msgs = { git = "https://github.com/ZettaScaleLabs/hiroz.git", branch = "main"}
mini-nav-controller = { path = "../mini-nav-controller" }
mini-nav-mapping = { path = "../mini-nav-mapping" }
mini-nav-planner = { path = "../mini-nav-planner" }
serde.workspace = true
serde_yaml.workspace = true
zenoh = "1.9.0"
rayon = "1.12.0"
anyhow = "1.0.104"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"

[[bin]]
name = "publisher"
path = "bin/publisher.rs"

[[bin]]
name = "a_star_planner"
path = "bin/a_star_planner.rs"

[[bin]]
name = "planner"
path = "bin/planner.rs"

[[bin]]
name = "example"
path = "bin/example.rs"
